### ISSUE TITLE
Implement workspace members

### ISSUE THREAD

**Issue by baszalmstra** [prefix-dev/pixi-build-backends#107]
In [#2945](https://github.com/prefix-dev/pixi-build-backends/issues/2945) we came to the following conclusion:  
  
We try to follow Cargo as close as possible, but also checked out how uv differs from Cargo

* Cargo is explicit about `members` and we plan to do the same
* Cargo adds `workspace.dependencies`, we don't plan to do that at the moment, because we expect a lot of use cases to be covered by variants
* Unlike Cargo, we also want to be able to inherit workspace members
* Like Cargo
  * if you have a path dependency, you specify the path to the package
  * if you have a git or url dependency, you specify the path to the workspace. The package path will be inferred.

```toml
# pixi.toml
[workspace]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["win-64", "linux-64", "osx-arm64", "osx-64"]
preview = ["pixi-build"]
members = ["packages/*"] 

[dependencies]
rich_example = { member = true }  # Path dependency
python_bindings = { git = "https://github.com/prefix-dev/cool_project" }
```

This issue is about implementing the `members` functionality.
