### ISSUE TITLE
Error on using target platforms

### ISSUE THREAD

**Issue by ruben-arts** [prefix-dev/pixi-build-backends#134]
This example will return you a strange error:

```toml
[workspace]
channels = ["https://prefix.dev/conda-forge"]
name = "test-build"
platforms = ["osx-arm64"]
preview = ["pixi-build"]

[package]
name = "pixi-test"
version = "0.45.0"

[package.build]
backend = { name = "pixi-build-rust", version = "*" }
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge"
]

[package.build-dependencies]
compilers = ">=1.9.0,<2"

# The culprit!
[package.target.osx-arm64.build-dependencies]
compilers = ">=1.6.0"
```

```
❯ pixi build
Error:   × unable to setup the build-backend to build the workspace
  ├─▶ received invalid response from the build backend (pixi-build-rust) when calling 'initialize'
  ╰─▶ key must be a string
```

These don't give an error:
- `package.target.unix.build-dependencies`
- `package.target.win.build-dependencies`
