### ISSUE TITLE
pixi-build-cmake: should get cmake override from build-dependencies instead of host

### ISSUE THREAD

**Issue by tdejager** [prefix-dev/pixi-build-backends#41]
Currently you need to do something like, to override the used cmake:

```toml
[host-dependencies]
cmake = ">=3.18, <3.27"
```

But it should be:

```toml
[build-dependencies]
cmake = ">=3.18, <3.27"
```
