### ISSUE TITLE
Variants should work for all backend not only the recipe backend.

### ISSUE THREAD

**Issue by tdejager** [prefix-dev/pixi-build-backends#42]
Currently one can create variants in the pixi.toml file when using the build feature:

```toml
        [workspace.build-variants]
        python = ["3.10.*", "3.11.*"]
```

However, this only works with the recipe backend currently. This should be possible for all backends.

A pointer to get started on this is to look at the `Output` struct used by the backends and use it similar to the recipe backend. This could require a rattler-build change to get to work nicely.
