### ISSUE TITLE
pixi-build-python backend needs a way to specify the source path

### ISSUE THREAD

**Issue by rgommers** [prefix-dev/pixi-build-backends#88]
In my dev setup (https://github.com/rgommers/pixi-dev-scipystack/) I consistently put `pixi.toml` files one level up from the root of the individual packages. With the `pixi-build-rattler-build` backend it is possible to point at such a location, because in `recipe.yaml` one can put an arbitrary source path with:
```
source:
  path: path-to-dir-with-pyproject.toml
```

With `pixi-build-python` I didn't find a way to specify a custom path. Inside `pixi.toml` this is usually done with `cwd = `, so I had expected something like this to work:
```toml
backend = { "pixi-build-python", version = "0.1.*", cwd = "path-to-dir-with-pyproject.toml" }
```
or alternatively:
```toml
backend = { "pixi-build-python", version = "0.1.*" }
path = "path-to-dir-with-pyproject.toml"
```

I'll note that the `pip` invocation does use an `$SRC_DIR`, but there seems to be no way to set `SRC_DIR`:
```
+ $PREFIX/bin/python -m pip install --ignore-installed -vv --no-deps --no-build-isolation $SRC_DIR
```

**Comment by baszalmstra** [comment]
I actually think this might apply to all backends!

```toml
[package.build]
backend = { name = "foobar", version = "1.*" }
source-root = "../" # A path relative to the directory that contains this file.
```
